services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    mem_limit: 1g
  redis:
    image: redis
    ports:
      - "6379:6379"
    mem_limit: 256g
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: openlibrary-server
      MINIO_ROOT_PASSWORD: IDsoRiCoNaTIcKLETringRoTA
    volumes:
      - s3_data:/data
    command: server /data --console-address ":9001"
    mem_limit: 512m
  elastic:
    image: elasticsearch:9.0.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
    mem_limit: 1g

volumes:
  s3_data:
  db_data: