services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: openlibrary-server
      MINIO_ROOT_PASSWORD: IDsoRiCoNaTIcKLETringRoTA
    volumes:
      - s3_data:/data
    command: server /data --console-address ":9001"

volumes:
  s3_data:
  db_data: