// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func serverData(data map[string]interface{}) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_serverData_96af`,
		Function: `function __templ_serverData_96af(data){window.__server__ = window.__server__ || {};
	Object.assign(window.__server__, data);
}`,
		Call:       templ.SafeScript(`__templ_serverData_96af`, data),
		CallInline: templ.SafeScriptInline(`__templ_serverData_96af`, data),
	}
}

var _ = templruntime.GeneratedTemplate
