// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForAnalytics_InsertEvent implements pgx.CopyFromSource.
type iteratorForAnalytics_InsertEvent struct {
	rows                 []Analytics_InsertEventParams
	skippedFirstNextCall bool
}

func (r *iteratorForAnalytics_InsertEvent) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAnalytics_InsertEvent) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserKey,
		r.rows[0].BookID,
		r.rows[0].EventType,
		r.rows[0].Value,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForAnalytics_InsertEvent) Err() error {
	return nil
}

func (q *Queries) Analytics_InsertEvent(ctx context.Context, arg []Analytics_InsertEventParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"ol_analytics", "interaction_event"}, []string{"user_key", "book_id", "event_type", "value", "created_at"}, &iteratorForAnalytics_InsertEvent{rows: arg})
}

// iteratorForInsertDefinedTagEnMasse implements pgx.CopyFromSource.
type iteratorForInsertDefinedTagEnMasse struct {
	rows                 []InsertDefinedTagEnMasseParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertDefinedTagEnMasse) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertDefinedTagEnMasse) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].IsSpoiler,
		r.rows[0].IsAdult,
		r.rows[0].CreatedAt,
		r.rows[0].TagType,
		r.rows[0].SynonymOf,
	}, nil
}

func (r iteratorForInsertDefinedTagEnMasse) Err() error {
	return nil
}

func (q *Queries) InsertDefinedTagEnMasse(ctx context.Context, arg []InsertDefinedTagEnMasseParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"defined_tags"}, []string{"id", "name", "description", "is_spoiler", "is_adult", "created_at", "tag_type", "synonym_of"}, &iteratorForInsertDefinedTagEnMasse{rows: arg})
}
