// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID           int64
	Name         string
	AuthorUserID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type BookChapter struct {
	ID        int64
	Name      pgtype.Text
	BookID    int64
	Content   string
	Order     int32
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID        string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UserAgent string
	IpAddress string
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Name         string
	JoinedAt     pgtype.Timestamptz
	PasswordHash string
}
