// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AgeRating string

const (
	AgeRatingValue0 AgeRating = "?"
	AgeRatingG      AgeRating = "G"
	AgeRatingPG     AgeRating = "PG"
	AgeRatingPG13   AgeRating = "PG-13"
	AgeRatingR      AgeRating = "R"
	AgeRatingNC17   AgeRating = "NC-17"
)

func (e *AgeRating) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgeRating(s)
	case string:
		*e = AgeRating(s)
	default:
		return fmt.Errorf("unsupported scan type for AgeRating: %T", src)
	}
	return nil
}

type NullAgeRating struct {
	AgeRating AgeRating
	Valid     bool // Valid is true if AgeRating is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgeRating) Scan(value interface{}) error {
	if value == nil {
		ns.AgeRating, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgeRating.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgeRating) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgeRating), nil
}

type TagType string

const (
	TagTypeFreeform TagType = "freeform"
	TagTypeWarning  TagType = "warning"
	TagTypeFandom   TagType = "fandom"
	TagTypeReltype  TagType = "reltype"
	TagTypeRel      TagType = "rel"
)

func (e *TagType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TagType(s)
	case string:
		*e = TagType(s)
	default:
		return fmt.Errorf("unsupported scan type for TagType: %T", src)
	}
	return nil
}

type NullTagType struct {
	TagType TagType
	Valid   bool // Valid is true if TagType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTagType) Scan(value interface{}) error {
	if value == nil {
		ns.TagType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TagType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTagType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TagType), nil
}

type Book struct {
	ID                 int64
	Name               string
	Summary            string
	AuthorUserID       pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	AgeRating          AgeRating
	IsPubliclyVisible  bool
	IsBanned           bool
	Words              int32
	Chapters           int32
	TagIds             []int64
	CachedParentTagIds []int64
	Favorites          int32
}

type BookBanHistory struct {
	BookID    int64
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Reason    string
	Action    string
}

type BookChapter struct {
	ID              int64
	Name            string
	BookID          int64
	Content         string
	Order           int32
	CreatedAt       pgtype.Timestamptz
	Words           int32
	IsAdultOverride bool
	Summary         string
}

type Collection struct {
	ID         int64
	Name       string
	UserID     pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	BooksCount int32
}

type CollectionBook struct {
	CollectionID int64
	BookID       int64
	Order        int32
}

type DefinedTag struct {
	ID             int64
	Name           string
	Description    string
	IsSpoiler      bool
	IsAdult        bool
	CreatedAt      pgtype.Timestamptz
	TagType        TagType
	SynonymOf      pgtype.Int8
	IsDefault      bool
	LowercasedName string
}

type Favorite struct {
	UserID     pgtype.UUID
	BookID     int64
	IsFavorite bool
	CreatedAt  pgtype.Timestamptz
}

type Session struct {
	ID        string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UserAgent string
	IpAddress string
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Name         string
	JoinedAt     pgtype.Timestamptz
	PasswordHash string
}
