// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.moderation.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const moderation_AddCommentLog = `-- name: Moderation_AddCommentLog :exec
insert into comment_logs (id, "time", comment_id, action_type, payload, actor_user_id, reason)
values ($1, $2, $3, $4, $5, $6, $7)
`

type Moderation_AddCommentLogParams struct {
	ID          int64
	Time        pgtype.Timestamptz
	CommentID   int64
	ActionType  string
	Payload     []byte
	ActorUserID pgtype.UUID
	Reason      string
}

func (q *Queries) Moderation_AddCommentLog(ctx context.Context, arg Moderation_AddCommentLogParams) error {
	_, err := q.db.Exec(ctx, moderation_AddCommentLog,
		arg.ID,
		arg.Time,
		arg.CommentID,
		arg.ActionType,
		arg.Payload,
		arg.ActorUserID,
		arg.Reason,
	)
	return err
}

const moderation_AddUserBan = `-- name: Moderation_AddUserBan :exec
insert into user_bans (id, user_id, created_at, banned_by_user_id, note, expires_at)
values ($1, $2, $3, $4, $5, $6)
`

type Moderation_AddUserBanParams struct {
	ID             int64
	UserID         pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	BannedByUserID pgtype.UUID
	Note           string
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) Moderation_AddUserBan(ctx context.Context, arg Moderation_AddUserBanParams) error {
	_, err := q.db.Exec(ctx, moderation_AddUserBan,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.BannedByUserID,
		arg.Note,
		arg.ExpiresAt,
	)
	return err
}

const moderation_AddUserLog = `-- name: Moderation_AddUserLog :exec
insert into user_logs (id, user_id, actor_user_id, action_type, payload, "time", reason)
values ($1, $2, $3, $4, $5, $6, $7)
`

type Moderation_AddUserLogParams struct {
	ID          int64
	UserID      pgtype.UUID
	ActorUserID pgtype.UUID
	ActionType  string
	Payload     []byte
	Time        pgtype.Timestamptz
	Reason      string
}

func (q *Queries) Moderation_AddUserLog(ctx context.Context, arg Moderation_AddUserLogParams) error {
	_, err := q.db.Exec(ctx, moderation_AddUserLog,
		arg.ID,
		arg.UserID,
		arg.ActorUserID,
		arg.ActionType,
		arg.Payload,
		arg.Time,
		arg.Reason,
	)
	return err
}

const moderation_ChangeUserAbout = `-- name: Moderation_ChangeUserAbout :exec
update users set about = $2 where id = $1
`

type Moderation_ChangeUserAboutParams struct {
	ID    pgtype.UUID
	About string
}

func (q *Queries) Moderation_ChangeUserAbout(ctx context.Context, arg Moderation_ChangeUserAboutParams) error {
	_, err := q.db.Exec(ctx, moderation_ChangeUserAbout, arg.ID, arg.About)
	return err
}

const moderation_GetChapter = `-- name: Moderation_GetChapter :one
select id, name, book_id, content, content_updated_at, "order", created_at, updated_at, words, summary, is_publicly_visible from book_chapters where id = $1
`

func (q *Queries) Moderation_GetChapter(ctx context.Context, id int64) (BookChapter, error) {
	row := q.db.QueryRow(ctx, moderation_GetChapter, id)
	var i BookChapter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BookID,
		&i.Content,
		&i.ContentUpdatedAt,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Words,
		&i.Summary,
		&i.IsPubliclyVisible,
	)
	return i, err
}

const moderation_GetLatestUserBanExpiry = `-- name: Moderation_GetLatestUserBanExpiry :one
select expires_at from user_bans where user_id = $1 order by created_at desc limit 1
`

func (q *Queries) Moderation_GetLatestUserBanExpiry(ctx context.Context, userID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, moderation_GetLatestUserBanExpiry, userID)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const moderation_GetUserLoginHistory = `-- name: Moderation_GetUserLoginHistory :many
select id, user_id, created_at, user_agent, ip_address
from sessions
where user_id = $1
order by created_at desc
`

type Moderation_GetUserLoginHistoryRow struct {
	ID        int64
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UserAgent string
	IpAddress string
}

func (q *Queries) Moderation_GetUserLoginHistory(ctx context.Context, userID pgtype.UUID) ([]Moderation_GetUserLoginHistoryRow, error) {
	rows, err := q.db.Query(ctx, moderation_GetUserLoginHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Moderation_GetUserLoginHistoryRow
	for rows.Next() {
		var i Moderation_GetUserLoginHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UserAgent,
			&i.IpAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moderation_RenameUser = `-- name: Moderation_RenameUser :exec
update users set name = $2 where id = $1
`

type Moderation_RenameUserParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) Moderation_RenameUser(ctx context.Context, arg Moderation_RenameUserParams) error {
	_, err := q.db.Exec(ctx, moderation_RenameUser, arg.ID, arg.Name)
	return err
}

const moderation_SetChapterVisibility = `-- name: Moderation_SetChapterVisibility :exec
update book_chapters set is_publicly_visible = $2, updated_at = now() where id = $1
`

type Moderation_SetChapterVisibilityParams struct {
	ID                int64
	IsPubliclyVisible bool
}

func (q *Queries) Moderation_SetChapterVisibility(ctx context.Context, arg Moderation_SetChapterVisibilityParams) error {
	_, err := q.db.Exec(ctx, moderation_SetChapterVisibility, arg.ID, arg.IsPubliclyVisible)
	return err
}

const moderation_SetCommentRemoved = `-- name: Moderation_SetCommentRemoved :exec
update comments
set deleted_at = case when $2::bool then now() else null end,
    updated_at = now()
where id = $1
`

type Moderation_SetCommentRemovedParams struct {
	ID      int64
	Removed bool
}

func (q *Queries) Moderation_SetCommentRemoved(ctx context.Context, arg Moderation_SetCommentRemovedParams) error {
	_, err := q.db.Exec(ctx, moderation_SetCommentRemoved, arg.ID, arg.Removed)
	return err
}

const moderation_SetUserBanned = `-- name: Moderation_SetUserBanned :exec
update users set is_banned = $2 where id = $1
`

type Moderation_SetUserBannedParams struct {
	ID       pgtype.UUID
	IsBanned bool
}

func (q *Queries) Moderation_SetUserBanned(ctx context.Context, arg Moderation_SetUserBannedParams) error {
	_, err := q.db.Exec(ctx, moderation_SetUserBanned, arg.ID, arg.IsBanned)
	return err
}
