// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.notifications.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const notification_DeleteByKey = `-- name: Notification_DeleteByKey :exec
delete from notifications where key = $1
`

func (q *Queries) Notification_DeleteByKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, notification_DeleteByKey, key)
	return err
}

const notification_DeleteByUserID = `-- name: Notification_DeleteByUserID :exec
delete from notifications where user_id = $1
`

func (q *Queries) Notification_DeleteByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, notification_DeleteByUserID, userID)
	return err
}

const notification_Get = `-- name: Notification_Get :one
select id, key, user_id, created_at, type, title, content, metadata from notifications where key = $1
`

func (q *Queries) Notification_Get(ctx context.Context, key string) (Notification, error) {
	row := q.db.QueryRow(ctx, notification_Get, key)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.CreatedAt,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.Metadata,
	)
	return i, err
}

const notification_Query = `-- name: Notification_Query :many
select id, key, user_id, created_at, type, title, content, metadata
from notifications
where user_id = $1
order by created_at desc
limit $2
`

type Notification_QueryParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) Notification_Query(ctx context.Context, arg Notification_QueryParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, notification_Query, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.UserID,
			&i.CreatedAt,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notification_QueryAfter = `-- name: Notification_QueryAfter :many
select id, key, user_id, created_at, type, title, content, metadata
from notifications
where user_id = $1 and created_at > $2
order by created_at desc
limit $3
`

type Notification_QueryAfterParams struct {
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Limit     int32
}

func (q *Queries) Notification_QueryAfter(ctx context.Context, arg Notification_QueryAfterParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, notification_QueryAfter, arg.UserID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.UserID,
			&i.CreatedAt,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notification_QueryBefore = `-- name: Notification_QueryBefore :many
select id, key, user_id, created_at, type, title, content, metadata
from notifications
where user_id = $1 and created_at < $2
order by created_at desc
limit $3
`

type Notification_QueryBeforeParams struct {
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Limit     int32
}

func (q *Queries) Notification_QueryBefore(ctx context.Context, arg Notification_QueryBeforeParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, notification_QueryBefore, arg.UserID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.UserID,
			&i.CreatedAt,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notification_Upsert = `-- name: Notification_Upsert :one
insert into notifications (key, user_id, created_at, "type", title, content, metadata)
values ($1, $2, $3, $4, $5, $6, $7)
on conflict (user_id, key) do update set
    created_at = EXCLUDED.created_at,
    content = EXCLUDED.content,
    metadata = EXCLUDED.metadata,
    title = EXCLUDED.title
returning id
`

type Notification_UpsertParams struct {
	Key       string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Type      string
	Title     string
	Content   string
	Metadata  []byte
}

func (q *Queries) Notification_Upsert(ctx context.Context, arg Notification_UpsertParams) (int64, error) {
	row := q.db.QueryRow(ctx, notification_Upsert,
		arg.Key,
		arg.UserID,
		arg.CreatedAt,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.Metadata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
