// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sitecfg.sql

package store

import (
	"context"
)

const siteConfig_Get = `-- name: SiteConfig_Get :one
select "value" from site_config
where "key" = 'main'
`

func (q *Queries) SiteConfig_Get(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, siteConfig_Get)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const siteConfig_Set = `-- name: SiteConfig_Set :exec
insert into site_config ("key", "value")
values ('main', $1)
on conflict ("key") do update set "value" = EXCLUDED."value"
`

func (q *Queries) SiteConfig_Set(ctx context.Context, value []byte) error {
	_, err := q.db.Exec(ctx, siteConfig_Set, value)
	return err
}
