// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sitecfg.sql

package store

import (
	"context"
)

const siteConfig_Get = `-- name: SiteConfig_Get :one
select jsonb_object_agg(key, value)::jsonb as value
from site_config
having count(*) > 0
`

// Assemble the typed application snapshot from independent settings rows.
func (q *Queries) SiteConfig_Get(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, siteConfig_Get)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const siteConfig_Set = `-- name: SiteConfig_Set :exec
insert into site_config (key, value)
select setting.key, setting.value
from jsonb_each($1::jsonb) setting
on conflict (key) do update set value = excluded.value
`

// A single statement keeps settings and their migration version consistent.
func (q *Queries) SiteConfig_Set(ctx context.Context, settings []byte) error {
	_, err := q.db.Exec(ctx, siteConfig_Set, settings)
	return err
}
