// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.draft.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const chapter_UserCanEdit = `-- name: Chapter_UserCanEdit :one
select exists (
    select 1
    from book_chapters
    join books on books.id = book_chapters.book_id
    where book_chapters.id = $1
	  and books.id = $2
      and books.author_user_id = $3
)
`

type Chapter_UserCanEditParams struct {
	ChapterID int64
	BookID    int64
	UserID    pgtype.UUID
}

func (q *Queries) Chapter_UserCanEdit(ctx context.Context, arg Chapter_UserCanEditParams) (bool, error) {
	row := q.db.QueryRow(ctx, chapter_UserCanEdit, arg.ChapterID, arg.BookID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const draft_ClearChapterSchedules = `-- name: Draft_ClearChapterSchedules :exec
update drafts set scheduled_at = null where chapter_id = $1
`

func (q *Queries) Draft_ClearChapterSchedules(ctx context.Context, chapterID int64) error {
	_, err := q.db.Exec(ctx, draft_ClearChapterSchedules, chapterID)
	return err
}

const draft_Delete = `-- name: Draft_Delete :exec
delete from drafts where id = $1
`

func (q *Queries) Draft_Delete(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, draft_Delete, id)
	return err
}

const draft_GetById = `-- name: Draft_GetById :one
select drafts.id, drafts.created_by, drafts.chapter_id, drafts.chapter_name, drafts.content, drafts.words, drafts.summary, drafts.updated_at, drafts.created_at, drafts.published_at, drafts.scheduled_at,
    books.id as book_id, books.name as book_name, 
    bc.is_publicly_visible as is_chapter_publicly_visible,
    bc.content_updated_at as chapter_content_updated_at,
    bc.fonts as chapter_fonts
from drafts
join book_chapters bc on bc.id = drafts.chapter_id
join books on books.id = bc.book_id
where drafts.id = $1
`

type Draft_GetByIdRow struct {
	ID                       int64
	CreatedBy                pgtype.UUID
	ChapterID                int64
	ChapterName              string
	Content                  string
	Words                    int32
	Summary                  string
	UpdatedAt                pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	PublishedAt              pgtype.Timestamptz
	ScheduledAt              pgtype.Timestamptz
	BookID                   int64
	BookName                 string
	IsChapterPubliclyVisible bool
	ChapterContentUpdatedAt  pgtype.Timestamptz
	ChapterFonts             []string
}

func (q *Queries) Draft_GetById(ctx context.Context, id int64) (Draft_GetByIdRow, error) {
	row := q.db.QueryRow(ctx, draft_GetById, id)
	var i Draft_GetByIdRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.ChapterID,
		&i.ChapterName,
		&i.Content,
		&i.Words,
		&i.Summary,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.BookID,
		&i.BookName,
		&i.IsChapterPubliclyVisible,
		&i.ChapterContentUpdatedAt,
		&i.ChapterFonts,
	)
	return i, err
}

const draft_GetLatestID = `-- name: Draft_GetLatestID :one
select id
from drafts
where chapter_id = $1
order by coalesce(updated_at, created_at) desc
limit 1
`

func (q *Queries) Draft_GetLatestID(ctx context.Context, chapterID int64) (int64, error) {
	row := q.db.QueryRow(ctx, draft_GetLatestID, chapterID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const draft_Insert = `-- name: Draft_Insert :exec
insert into drafts (
    id, created_by, chapter_id, chapter_name, content, updated_at, created_at)
values ($1, $2, $3, $4, $5, $6, $7)
`

type Draft_InsertParams struct {
	ID          int64
	CreatedBy   pgtype.UUID
	ChapterID   int64
	ChapterName string
	Content     string
	UpdatedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) Draft_Insert(ctx context.Context, arg Draft_InsertParams) error {
	_, err := q.db.Exec(ctx, draft_Insert,
		arg.ID,
		arg.CreatedBy,
		arg.ChapterID,
		arg.ChapterName,
		arg.Content,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	return err
}

const draft_MarkAsPublished = `-- name: Draft_MarkAsPublished :exec
update drafts
set published_at = now(), scheduled_at = null
where id = $1
`

func (q *Queries) Draft_MarkAsPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, draft_MarkAsPublished, id)
	return err
}

const draft_PublishDue = `-- name: Draft_PublishDue :many
with due as (
    select drafts.id, drafts.created_by, drafts.chapter_id, drafts.chapter_name, drafts.content, drafts.words, drafts.summary, drafts.updated_at, drafts.created_at, drafts.published_at, drafts.scheduled_at
    from drafts
    where scheduled_at <= now()
    for update skip locked
), updated_chapters as (
    update book_chapters
    set name = due.chapter_name,
        content = due.content,
        words = due.words,
        summary = due.summary,
        is_publicly_visible = true,
        content_updated_at = due.updated_at,
        updated_at = now()
    from due
    where book_chapters.id = due.chapter_id
    returning book_chapters.book_id, due.id as draft_id
), published_drafts as (
    update drafts
    set published_at = now(), scheduled_at = null
    from updated_chapters
    where drafts.id = updated_chapters.draft_id
)
select distinct book_id from updated_chapters
`

func (q *Queries) Draft_PublishDue(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, draft_PublishDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var book_id int64
		if err := rows.Scan(&book_id); err != nil {
			return nil, err
		}
		items = append(items, book_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const draft_Schedule = `-- name: Draft_Schedule :exec
update drafts set scheduled_at = $2, updated_at = now() where id = $1
`

type Draft_ScheduleParams struct {
	ID          int64
	ScheduledAt pgtype.Timestamptz
}

func (q *Queries) Draft_Schedule(ctx context.Context, arg Draft_ScheduleParams) error {
	_, err := q.db.Exec(ctx, draft_Schedule, arg.ID, arg.ScheduledAt)
	return err
}

const draft_Update = `-- name: Draft_Update :exec
update drafts
set chapter_name = $2, words = $3, content = $4, summary = $5, updated_at = now()
where id = $1
`

type Draft_UpdateParams struct {
	ID          int64
	ChapterName string
	Words       int32
	Content     string
	Summary     string
}

func (q *Queries) Draft_Update(ctx context.Context, arg Draft_UpdateParams) error {
	_, err := q.db.Exec(ctx, draft_Update,
		arg.ID,
		arg.ChapterName,
		arg.Words,
		arg.Content,
		arg.Summary,
	)
	return err
}

const draft_UpdateChapterName = `-- name: Draft_UpdateChapterName :exec
update drafts
set chapter_name = $2, updated_at = now()
where id = $1
`

type Draft_UpdateChapterNameParams struct {
	ID          int64
	ChapterName string
}

func (q *Queries) Draft_UpdateChapterName(ctx context.Context, arg Draft_UpdateChapterNameParams) error {
	_, err := q.db.Exec(ctx, draft_UpdateChapterName, arg.ID, arg.ChapterName)
	return err
}

const draft_UpdateContent = `-- name: Draft_UpdateContent :exec
update drafts
set content = $2, words = $3, updated_at = now()
where id = $1
`

type Draft_UpdateContentParams struct {
	ID      int64
	Content string
	Words   int32
}

func (q *Queries) Draft_UpdateContent(ctx context.Context, arg Draft_UpdateContentParams) error {
	_, err := q.db.Exec(ctx, draft_UpdateContent, arg.ID, arg.Content, arg.Words)
	return err
}

const draft_UserCanAccess = `-- name: Draft_UserCanAccess :one
select exists (
    select 1
    from drafts
    join book_chapters on book_chapters.id = drafts.chapter_id
    join books on books.id = book_chapters.book_id
    where drafts.id = $1
      and books.author_user_id = $2
      and ($3::int8 = 0 or book_chapters.id = $3)
      and ($4::int8 = 0 or books.id = $4)
)
`

type Draft_UserCanAccessParams struct {
	DraftID   int64
	UserID    pgtype.UUID
	ChapterID int64
	BookID    int64
}

func (q *Queries) Draft_UserCanAccess(ctx context.Context, arg Draft_UserCanAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, draft_UserCanAccess,
		arg.DraftID,
		arg.UserID,
		arg.ChapterID,
		arg.BookID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
