// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.analytics.sql

package store

import (
	"context"
)

const analytics_GetMetricValue = `-- name: Analytics_GetMetricValue :one
select samples_count, value_sum
from ol_analytics.bucket
where bucket_type = $1 and book_id = $2 and metric = $3
`

type Analytics_GetMetricValueParams struct {
	BucketType OlAnalyticsBucketPeriodType
	BookID     int64
	Metric     string
}

type Analytics_GetMetricValueRow struct {
	SamplesCount int64
	ValueSum     float64
}

func (q *Queries) Analytics_GetMetricValue(ctx context.Context, arg Analytics_GetMetricValueParams) (Analytics_GetMetricValueRow, error) {
	row := q.db.QueryRow(ctx, analytics_GetMetricValue, arg.BucketType, arg.BookID, arg.Metric)
	var i Analytics_GetMetricValueRow
	err := row.Scan(&i.SamplesCount, &i.ValueSum)
	return i, err
}

const analytics_GetMetricValues = `-- name: Analytics_GetMetricValues :many
select book_id, metric, bucket_type, samples_count, value_sum
from ol_analytics.bucket
where book_id = ANY($2::int8[]) and metric = $1
`

type Analytics_GetMetricValuesParams struct {
	Metric  string
	BookIds []int64
}

type Analytics_GetMetricValuesRow struct {
	BookID       int64
	Metric       string
	BucketType   OlAnalyticsBucketPeriodType
	SamplesCount int64
	ValueSum     float64
}

func (q *Queries) Analytics_GetMetricValues(ctx context.Context, arg Analytics_GetMetricValuesParams) ([]Analytics_GetMetricValuesRow, error) {
	rows, err := q.db.Query(ctx, analytics_GetMetricValues, arg.Metric, arg.BookIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Analytics_GetMetricValuesRow
	for rows.Next() {
		var i Analytics_GetMetricValuesRow
		if err := rows.Scan(
			&i.BookID,
			&i.Metric,
			&i.BucketType,
			&i.SamplesCount,
			&i.ValueSum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type Analytics_InsertEventParams struct {
	UserKey   string
	BookID    int64
	EventType string
	Value     float64
}

const analytics_UpdateMetrics = `-- name: Analytics_UpdateMetrics :exec
WITH 
    input_rows AS (
        SELECT
            ($1::bigint[])[i] AS book_id,
            ($2::text[])[i] AS metric,
            ($3::double precision[])[i] AS increment_value
        FROM generate_subscripts(
            $1::bigint[],
            1
        ) AS indexes(i)
    ),
    bucket_definitions AS (
        SELECT
            'all'::ol_analytics.bucket_period_type AS bucket_type,
            TIMESTAMPTZ '1970-01-01 00:00:00+00' AS bucket_start

        UNION ALL

        SELECT
            'year'::ol_analytics.bucket_period_type,
            date_trunc('year', now(), 'UTC')

        UNION ALL

        SELECT
            'month'::ol_analytics.bucket_period_type,
            date_trunc('month', now(), 'UTC')

        UNION ALL

        SELECT
            'week'::ol_analytics.bucket_period_type,
            date_trunc('week', now(), 'UTC')

        UNION ALL

        SELECT
            'day'::ol_analytics.bucket_period_type,
            date_trunc('day', now(), 'UTC')
    ),
    aggregated_buckets AS (
        SELECT
            input.book_id,
            input.metric,
            buckets.bucket_type,
            buckets.bucket_start,
            sum(input.increment_value) AS increment_value
        FROM input_rows AS input
        CROSS JOIN bucket_definitions AS buckets
        GROUP BY
            input.book_id,
            input.metric,
            buckets.bucket_type,
            buckets.bucket_start
    )
INSERT INTO ol_analytics.bucket (
    book_id,
    metric,
    bucket_type,
    bucket_start,
    value_sum,
    samples_count
)
SELECT
    book_id,
    metric,
    bucket_type,
    bucket_start,
    increment_value,
    1
FROM aggregated_buckets
ON CONFLICT (
    book_id,
    metric,
    bucket_type,
    bucket_start
)
DO UPDATE SET
    value = ol_analytics.bucket.value + EXCLUDED.value,
    samples_count = ol_analytics.bucket.samples_count + 1,
    updated_at = now()
`

type Analytics_UpdateMetricsParams struct {
	BookIds []int64
	Metrics []string
	Values  []float64
}

func (q *Queries) Analytics_UpdateMetrics(ctx context.Context, arg Analytics_UpdateMetricsParams) error {
	_, err := q.db.Exec(ctx, analytics_UpdateMetrics, arg.BookIds, arg.Metrics, arg.Values)
	return err
}

const analytics_UpdatePopularity = `-- name: Analytics_UpdatePopularity :exec
WITH 
    params AS (
        SELECT statement_timestamp() AS run_at
    ),
    expanded_events AS (
        SELECT
            event.book_id,
            event.event_type,
            event.created_at,
            event_bucket.bucket_type,
            event_bucket.bucket_start
        FROM ol_analytics.interaction_event AS event
        CROSS JOIN LATERAL (
            SELECT
                'all'::ol_analytics.bucket_period_type AS bucket_type,
                TIMESTAMPTZ '1970-01-01 00:00:00+00' AS bucket_start

            UNION ALL

            SELECT
                'year'::ol_analytics.bucket_period_type,
                date_trunc('year', event.created_at AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'

            UNION ALL

            SELECT
                'month'::ol_analytics.bucket_period_type,
                date_trunc('month', event.created_at AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'

            UNION ALL

            SELECT
                'week'::ol_analytics.bucket_period_type,
                date_trunc('week', event.created_at AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'

            UNION ALL

            SELECT
                'day'::ol_analytics.bucket_period_type,
                date_trunc('day', event.created_at AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
        ) AS event_bucket
    ),
    unprocessed_events AS (
        SELECT
            event.book_id, event.event_type, event.created_at, event.bucket_type, event.bucket_start,
            existing.updated_at AS previous_updated_at
        FROM expanded_events AS event
        LEFT JOIN ol_analytics.book_popularity_bucket AS existing
            ON existing.book_id = event.book_id
        AND existing.bucket_type = event.bucket_type
        AND existing.bucket_start = event.bucket_start
        WHERE event.created_at > COALESCE(
            existing.updated_at,
            TIMESTAMPTZ '-infinity'
        )
    ),
    new_scores AS (
        SELECT
            event.book_id,
            event.bucket_type,
            event.bucket_start,
            SUM(
                CASE event.event_type
                    WHEN 'book_view'
                        THEN $2::double precision
                    WHEN 'search_click'
                        THEN $3::double precision
                    WHEN 'chapter_view'
                        THEN $4::double precision
                    WHEN 'started_reading'
                        THEN $5::double precision
                    WHEN 'completed'
                        THEN $6::double precision
                    WHEN 'dropped'
                        THEN $7::double precision
                    WHEN 'finished_chapter'
                        THEN $8::double precision
                    ELSE 0
                END
                *
                POWER(
                    0.5,
                    EXTRACT(
                        EPOCH FROM params.run_at - event.created_at
                    )
                    / $1::double precision
                )
            ) AS value
        FROM unprocessed_events AS event
        CROSS JOIN params
        GROUP BY
            event.book_id,
            event.bucket_type,
            event.bucket_start
    )
INSERT INTO ol_analytics.book_popularity_bucket (
    book_id,
    bucket_type,
    bucket_start,
    value,
    updated_at
)
SELECT
    score.book_id,
    score.bucket_type,
    score.bucket_start,
    score.value,
    params.run_at
FROM new_scores AS score
CROSS JOIN params
ON CONFLICT (
    book_id,
    bucket_type,
    bucket_start
)
DO UPDATE SET
    value =
        ol_analytics.book_popularity_bucket.value
        * POWER(
            0.5,
            EXTRACT(
                EPOCH FROM (
                    EXCLUDED.updated_at
                    - ol_analytics.book_popularity_bucket.updated_at
                )
            )
            / $1::double precision
        )
        + EXCLUDED.value,
    updated_at = EXCLUDED.updated_at
`

type Analytics_UpdatePopularityParams struct {
	HalfLifeSeconds      float64
	BookViewScore        float64
	SearchClickScore     float64
	ChapterViewScore     float64
	StartedReadingScore  float64
	CompletedScore       float64
	DroppedScore         float64
	FinishedChapterScore float64
}

func (q *Queries) Analytics_UpdatePopularity(ctx context.Context, arg Analytics_UpdatePopularityParams) error {
	_, err := q.db.Exec(ctx, analytics_UpdatePopularity,
		arg.HalfLifeSeconds,
		arg.BookViewScore,
		arg.SearchClickScore,
		arg.ChapterViewScore,
		arg.StartedReadingScore,
		arg.CompletedScore,
		arg.DroppedScore,
		arg.FinishedChapterScore,
	)
	return err
}
