// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.reports.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const report_BookChapterExists = `-- name: Report_BookChapterExists :one
select exists(select 1 from book_chapters where id = $1 and book_id = $2)
`

type Report_BookChapterExistsParams struct {
	ChapterID int64
	BookID    int64
}

func (q *Queries) Report_BookChapterExists(ctx context.Context, arg Report_BookChapterExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, report_BookChapterExists, arg.ChapterID, arg.BookID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const report_BookExists = `-- name: Report_BookExists :one
select exists(select 1 from books where id = $1)
`

func (q *Queries) Report_BookExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, report_BookExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const report_CommentExists = `-- name: Report_CommentExists :one
select exists(select 1 from comments where id = $1)
`

func (q *Queries) Report_CommentExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, report_CommentExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const report_CountSearch = `-- name: Report_CountSearch :one
select count(*)
from reports
where
    ($1::text = ''
        or reports.number ilike '%' || $1 || '%'
        or reports.reason ilike '%' || $1 || '%'
        or reports.description ilike '%' || $1 || '%'
        or reports.target_id ilike '%' || $1 || '%')
    and ($2::text = '' or reports.target_type = $2)
`

type Report_CountSearchParams struct {
	Search     string
	TargetType string
}

func (q *Queries) Report_CountSearch(ctx context.Context, arg Report_CountSearchParams) (int64, error) {
	row := q.db.QueryRow(ctx, report_CountSearch, arg.Search, arg.TargetType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const report_Create = `-- name: Report_Create :one
with next_number as (
    insert into report_number_counters ("day", counter)
    values ((timezone('UTC', statement_timestamp()))::date, 1)
    on conflict ("day") do update
        set counter = report_number_counters.counter + 1
    returning "day", counter
)
insert into reports (number, "time", reporter_user_id, target_type, target_id, reason, description, book_chapter_id, book_excerpt)
select
    'R-' || to_char("day", 'YYYY-MMDD') || '-' || counter::text,
    $1, $2, $3,
    $4, $5, $6, $7, $8
from next_number
returning id, number
`

type Report_CreateParams struct {
	Time           pgtype.Timestamptz
	ReporterUserID pgtype.UUID
	TargetType     string
	TargetID       string
	Reason         string
	Description    string
	BookChapterID  pgtype.Int8
	BookExcerpt    string
}

type Report_CreateRow struct {
	ID     int64
	Number string
}

func (q *Queries) Report_Create(ctx context.Context, arg Report_CreateParams) (Report_CreateRow, error) {
	row := q.db.QueryRow(ctx, report_Create,
		arg.Time,
		arg.ReporterUserID,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
		arg.Description,
		arg.BookChapterID,
		arg.BookExcerpt,
	)
	var i Report_CreateRow
	err := row.Scan(&i.ID, &i.Number)
	return i, err
}

const report_GetBookContext = `-- name: Report_GetBookContext :one
select
    reports.book_chapter_id,
    reports.book_excerpt,
    books.id as book_id,
    books.name as title,
    authors.name as author,
    books.cover,
    book_chapters.name as chapter,
    books.age_rating,
    coalesce(array_agg(distinct defined_tags.name) filter (where defined_tags.id is not null), '{}')::text[] as warnings,
    books.is_perm_removed,
    books.is_banned,
    books.is_trashed,
    books.is_publicly_visible,
    books.created_at as book_created_at,
    book_chapters.created_at as chapter_created_at,
    book_chapters.updated_at as chapter_updated_at,
    book_chapters.content_updated_at as chapter_content_updated_at,
    (select count(*) from reports related where related.target_type = 'book' and related.target_id = reports.target_id)::int as related_reports
from reports
join books on books.id::text = reports.target_id
join users authors on authors.id = books.author_user_id
left join book_chapters on book_chapters.id = reports.book_chapter_id and book_chapters.book_id = books.id
left join defined_tags on defined_tags.id = any(books.tag_ids) and defined_tags.tag_type = 'warning'
where reports.id = $1 and reports.target_type = 'book'
group by reports.id, books.id, authors.name, book_chapters.id
`

type Report_GetBookContextRow struct {
	BookChapterID           pgtype.Int8
	BookExcerpt             string
	BookID                  int64
	Title                   string
	Author                  string
	Cover                   string
	Chapter                 pgtype.Text
	AgeRating               AgeRating
	Warnings                []string
	IsPermRemoved           bool
	IsBanned                bool
	IsTrashed               bool
	IsPubliclyVisible       bool
	BookCreatedAt           pgtype.Timestamptz
	ChapterCreatedAt        pgtype.Timestamptz
	ChapterUpdatedAt        pgtype.Timestamptz
	ChapterContentUpdatedAt pgtype.Timestamptz
	RelatedReports          int32
}

func (q *Queries) Report_GetBookContext(ctx context.Context, id int64) (Report_GetBookContextRow, error) {
	row := q.db.QueryRow(ctx, report_GetBookContext, id)
	var i Report_GetBookContextRow
	err := row.Scan(
		&i.BookChapterID,
		&i.BookExcerpt,
		&i.BookID,
		&i.Title,
		&i.Author,
		&i.Cover,
		&i.Chapter,
		&i.AgeRating,
		&i.Warnings,
		&i.IsPermRemoved,
		&i.IsBanned,
		&i.IsTrashed,
		&i.IsPubliclyVisible,
		&i.BookCreatedAt,
		&i.ChapterCreatedAt,
		&i.ChapterUpdatedAt,
		&i.ChapterContentUpdatedAt,
		&i.RelatedReports,
	)
	return i, err
}

const report_GetByID = `-- name: Report_GetByID :one
select reports.id, reports.number, reports.time, reports.reporter_user_id, reports.target_type, reports.target_id, reports.reason, reports.description, reports.book_chapter_id, reports.book_excerpt, reports.status, reports.priority, users.name as reporter_user_name
from reports
join users on users.id = reports.reporter_user_id
where reports.id = $1
`

type Report_GetByIDRow struct {
	ID               int64
	Number           string
	Time             pgtype.Timestamptz
	ReporterUserID   pgtype.UUID
	TargetType       string
	TargetID         string
	Reason           string
	Description      string
	BookChapterID    pgtype.Int8
	BookExcerpt      string
	Status           string
	Priority         string
	ReporterUserName string
}

func (q *Queries) Report_GetByID(ctx context.Context, id int64) (Report_GetByIDRow, error) {
	row := q.db.QueryRow(ctx, report_GetByID, id)
	var i Report_GetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Time,
		&i.ReporterUserID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Description,
		&i.BookChapterID,
		&i.BookExcerpt,
		&i.Status,
		&i.Priority,
		&i.ReporterUserName,
	)
	return i, err
}

const report_GetCommentContext = `-- name: Report_GetCommentContext :one
select comments.id, comments.content, comments.created_at, comments.updated_at, comments.deleted_at,
       authors.id as author_id, authors.name as author_name,
       book_chapters.id as chapter_id, book_chapters.name as chapter_name,
       books.id as book_id, books.name as book_name,
       (select count(*) from reports related where related.target_type = 'comment' and related.target_id = comments.id::text)::int as related_reports
from reports
join comments on comments.id = reports.target_id::bigint
join users authors on authors.id = comments.user_id
join book_chapters on book_chapters.id = comments.chapter_id
join books on books.id = book_chapters.book_id
where reports.id = $1 and reports.target_type = 'comment'
`

type Report_GetCommentContextRow struct {
	ID             int64
	Content        string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	AuthorID       pgtype.UUID
	AuthorName     string
	ChapterID      int64
	ChapterName    string
	BookID         int64
	BookName       string
	RelatedReports int32
}

func (q *Queries) Report_GetCommentContext(ctx context.Context, id int64) (Report_GetCommentContextRow, error) {
	row := q.db.QueryRow(ctx, report_GetCommentContext, id)
	var i Report_GetCommentContextRow
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AuthorID,
		&i.AuthorName,
		&i.ChapterID,
		&i.ChapterName,
		&i.BookID,
		&i.BookName,
		&i.RelatedReports,
	)
	return i, err
}

const report_GetEvents = `-- name: Report_GetEvents :many
select moderation_logs.id, moderation_logs.time, moderation_logs.type, moderation_logs.target_type, moderation_logs.target_id, moderation_logs.payload, moderation_logs.actor_user_id, moderation_logs.reason, users.name as actor_user_name
from moderation_logs
join users on users.id = moderation_logs.actor_user_id
where moderation_logs.target_type = 'report'
  and moderation_logs.target_id = $1::bigint::text
  and moderation_logs.type = 'report_decision'
order by moderation_logs.time, moderation_logs.id
`

type Report_GetEventsRow struct {
	ID            int64
	Time          pgtype.Timestamptz
	Type          string
	TargetType    string
	TargetID      string
	Payload       []byte
	ActorUserID   pgtype.UUID
	Reason        string
	ActorUserName string
}

func (q *Queries) Report_GetEvents(ctx context.Context, reportID int64) ([]Report_GetEventsRow, error) {
	rows, err := q.db.Query(ctx, report_GetEvents, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report_GetEventsRow
	for rows.Next() {
		var i Report_GetEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.Type,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.ActorUserID,
			&i.Reason,
			&i.ActorUserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const report_GetUserContext = `-- name: Report_GetUserContext :one
select users.id, users.name, users.email, users.about, users.joined_at, users.role, users.is_banned,
       (select count(*) from reports related where related.target_type = 'user' and related.target_id = users.id::text)::int as related_reports
from reports
join users on users.id = reports.target_id::uuid
where reports.id = $1 and reports.target_type = 'user'
`

type Report_GetUserContextRow struct {
	ID             pgtype.UUID
	Name           string
	Email          string
	About          string
	JoinedAt       pgtype.Timestamptz
	Role           UserRole
	IsBanned       bool
	RelatedReports int32
}

func (q *Queries) Report_GetUserContext(ctx context.Context, id int64) (Report_GetUserContextRow, error) {
	row := q.db.QueryRow(ctx, report_GetUserContext, id)
	var i Report_GetUserContextRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.About,
		&i.JoinedAt,
		&i.Role,
		&i.IsBanned,
		&i.RelatedReports,
	)
	return i, err
}

const report_Search = `-- name: Report_Search :many
select reports.id, reports.number, reports.time, reports.reporter_user_id, reports.target_type, reports.target_id, reports.reason, reports.description, reports.book_chapter_id, reports.book_excerpt, reports.status, reports.priority, users.name as reporter_user_name
from reports
join users on users.id = reports.reporter_user_id
where
    ($1::text = ''
        or reports.number ilike '%' || $1 || '%'
        or reports.reason ilike '%' || $1 || '%'
        or reports.description ilike '%' || $1 || '%'
        or reports.target_id ilike '%' || $1 || '%')
    and ($2::text = '' or reports.target_type = $2)
order by reports."time" desc, reports.id desc
limit $4 offset $3
`

type Report_SearchParams struct {
	Search     string
	TargetType string
	PageOffset int32
	PageLimit  int32
}

type Report_SearchRow struct {
	ID               int64
	Number           string
	Time             pgtype.Timestamptz
	ReporterUserID   pgtype.UUID
	TargetType       string
	TargetID         string
	Reason           string
	Description      string
	BookChapterID    pgtype.Int8
	BookExcerpt      string
	Status           string
	Priority         string
	ReporterUserName string
}

func (q *Queries) Report_Search(ctx context.Context, arg Report_SearchParams) ([]Report_SearchRow, error) {
	rows, err := q.db.Query(ctx, report_Search,
		arg.Search,
		arg.TargetType,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report_SearchRow
	for rows.Next() {
		var i Report_SearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Time,
			&i.ReporterUserID,
			&i.TargetType,
			&i.TargetID,
			&i.Reason,
			&i.Description,
			&i.BookChapterID,
			&i.BookExcerpt,
			&i.Status,
			&i.Priority,
			&i.ReporterUserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const report_SetStatus = `-- name: Report_SetStatus :execrows
update reports
set status = $1
where id = $2 and status in ('unreviewed', 'escalated')
`

type Report_SetStatusParams struct {
	NewStatus string
	ReportID  int64
}

func (q *Queries) Report_SetStatus(ctx context.Context, arg Report_SetStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, report_SetStatus, arg.NewStatus, arg.ReportID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const report_UserExists = `-- name: Report_UserExists :one
select exists(select 1 from users where id = $1)
`

func (q *Queries) Report_UserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, report_UserExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
