// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.analytics.sql

package store

import (
	"context"
)

const analytics_GetChapterViews = `-- name: Analytics_GetChapterViews :many
select "period", sum(view_count) as agg_view_count
from ol_analytics.view_counter
where
    book_id = $1 and entity_type = 1 and (
        "period" = 0 or
        "period" = $2 or
        "period" = $3 or
        "period" = $4 or
        "period" = $5 or
        "period" = $6
    )
group by entity_id
`

type Analytics_GetChapterViewsParams struct {
	BookID      int64
	YearPeriod  int32
	MonthPeriod int32
	WeekPeriod  int32
	DayPeriod   int32
	HourPeriod  int32
}

type Analytics_GetChapterViewsRow struct {
	Period       int32
	AggViewCount int64
}

func (q *Queries) Analytics_GetChapterViews(ctx context.Context, arg Analytics_GetChapterViewsParams) ([]Analytics_GetChapterViewsRow, error) {
	rows, err := q.db.Query(ctx, analytics_GetChapterViews,
		arg.BookID,
		arg.YearPeriod,
		arg.MonthPeriod,
		arg.WeekPeriod,
		arg.DayPeriod,
		arg.HourPeriod,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Analytics_GetChapterViewsRow
	for rows.Next() {
		var i Analytics_GetChapterViewsRow
		if err := rows.Scan(&i.Period, &i.AggViewCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analytics_GetMostViewedBooksByBookViewsOnly = `-- name: Analytics_GetMostViewedBooksByBookViewsOnly :many
select book_id, view_count
from ol_analytics.view_counter
where "period" = $1 and entity_type = 0
order by view_count desc
limit $2
`

type Analytics_GetMostViewedBooksByBookViewsOnlyParams struct {
	Period int32
	Limit  int32
}

type Analytics_GetMostViewedBooksByBookViewsOnlyRow struct {
	BookID    int64
	ViewCount int64
}

func (q *Queries) Analytics_GetMostViewedBooksByBookViewsOnly(ctx context.Context, arg Analytics_GetMostViewedBooksByBookViewsOnlyParams) ([]Analytics_GetMostViewedBooksByBookViewsOnlyRow, error) {
	rows, err := q.db.Query(ctx, analytics_GetMostViewedBooksByBookViewsOnly, arg.Period, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Analytics_GetMostViewedBooksByBookViewsOnlyRow
	for rows.Next() {
		var i Analytics_GetMostViewedBooksByBookViewsOnlyRow
		if err := rows.Scan(&i.BookID, &i.ViewCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analytics_GetTotalViews = `-- name: Analytics_GetTotalViews :one
select view_count
from ol_analytics.view_counter
where book_id = $1 and "period" = 0 and entity_type = 0
`

func (q *Queries) Analytics_GetTotalViews(ctx context.Context, bookID int64) (int64, error) {
	row := q.db.QueryRow(ctx, analytics_GetTotalViews, bookID)
	var view_count int64
	err := row.Scan(&view_count)
	return view_count, err
}

const analytics_GetViews = `-- name: Analytics_GetViews :many
select "period", view_count
from ol_analytics.view_counter
where 
    book_id = $1 and entity_type = 0 and (
        "period" = 0 or
        "period" = $2 or
        "period" = $3 or
        "period" = $4 or
        "period" = $5 or
        "period" = $6
    )
`

type Analytics_GetViewsParams struct {
	BookID      int64
	YearPeriod  int32
	MonthPeriod int32
	WeekPeriod  int32
	DayPeriod   int32
	HourPeriod  int32
}

type Analytics_GetViewsRow struct {
	Period    int32
	ViewCount int64
}

func (q *Queries) Analytics_GetViews(ctx context.Context, arg Analytics_GetViewsParams) ([]Analytics_GetViewsRow, error) {
	rows, err := q.db.Query(ctx, analytics_GetViews,
		arg.BookID,
		arg.YearPeriod,
		arg.MonthPeriod,
		arg.WeekPeriod,
		arg.DayPeriod,
		arg.HourPeriod,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Analytics_GetViewsRow
	for rows.Next() {
		var i Analytics_GetViewsRow
		if err := rows.Scan(&i.Period, &i.ViewCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analytics_IncrView = `-- name: Analytics_IncrView :exec
insert into ol_analytics.view_counter ("period", book_id, view_count, entity_type, entity_id)
values ($1, $2, $3, $4, $5)
on conflict (period, entity_type, entity_id)
do update set view_count = EXCLUDED.view_count + ol_analytics.view_bucket.view_count
`

type Analytics_IncrViewParams struct {
	Period     int32
	BookID     int64
	IncrBy     int64
	EntityType int16
	EntityID   int64
}

func (q *Queries) Analytics_IncrView(ctx context.Context, arg Analytics_IncrViewParams) error {
	_, err := q.db.Exec(ctx, analytics_IncrView,
		arg.Period,
		arg.BookID,
		arg.IncrBy,
		arg.EntityType,
		arg.EntityID,
	)
	return err
}
